# ${FACULTY_NUMBER} in this file should be replaced manually!
# This value should match the one in "deployment.yaml" file!
# It doesn't have to be the same as the one defined in "im.sh", "deploy.sh" and ".gitlab-ci.yaml" -
# other value can be chosen, but for simplicity, I would advise on using the same value.
apiVersion: v1
kind: Service
metadata:
  name: ${FACULTY_NUMBER}
  labels:
    app: ${FACULTY_NUMBER}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: ${FACULTY_NUMBER}
